### ISSUE TITLE
DeserializeObject fails on property with type Dictionary<TKey, TValue> where TKey is an Enum

### ISSUE THREAD

**Issue by primarilysoftware** [bridgedotnet/Bridge.Newtonsoft.Json#93]
We have a .NET WebAPI controller that is serializing a Person class which contains a property of type Dictionary<AddressType, Address> where AddressType is an enum.  We are attempting to share the same .cs source files between our WebAPI server code and Bridge.NET client code for Person, AddressType, and Address.  When calling DeserializeObject<Person> on the client, we get the following error:

Invalid Enumeration Value
    at ctor (http://localhost:63375/Scripts/bridge/bridge.js:5226:31)
    at new ctor (http://localhost:63375/Scripts/bridge/bridge.js:5409:35)
    at Function.parse (http://localhost:63375/Scripts/bridge/bridge.js:4441:23)
    at Function.DeserializeObject (http://localhost:63375/Scripts/bridge/newtonsoft.json.js:1196:61)
    at Function.DeserializeObject (http://localhost:63375/Scripts/bridge/newtonsoft.json.js:1255:84)
    at Function.DeserializeObject (http://localhost:63375/Scripts/bridge/newtonsoft.json.js:1402:78)
    at Function.DeserializeObject (http://localhost:63375/Scripts/bridge/newtonsoft.json.js:1402:78)

I tried to demonstrate the issue on Deck, but I think it is failing in a different way because metadata is not being produced:

https://deck.net/5ca0a241e9c94e02a82ace4ddb6f44ea

**Comment by fabriciomurta** [comment]
See also Bridge.NET forums' thread: [DeserializeObject fails on property with type Dictionary where TKey is an Enum](https://forums.bridge.net/forum/premium/premium-help/5373)

**Comment by fabriciomurta** [comment]
Deck reproducing the issue: https://deck.net/a17ac5321a9baa1e4075d2a5c33ad2b2

The string used here can be generated from native .NET if you run the same code, uncommenting the lines where it calls SerializeObject(). Corresponding dotnet fiddle (lines still commented out, like deck above): https://dotnetfiddle.net/xTQlOF
